changelog:
  change-template: "* $title #$number @$author"
  exclude:
    labels:
      - build
      - dependencies
      - documentation
      - invalid
      - java

  categories:
    - title: Fixes
      change-template: "* $title #$number @$author"
      labels:
        - bug

    - title: Features
      change-template: "* $title #$number @$author"
      labels:
        - enhancement

    - title: Other
      change-template: "* $title #$number @$author"
      labels:
        - '*'
